config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resource :counter, only: [:show] do
    member do
      post :reset
    end
  end
  root to: 'counters#show'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/counter.rb
# frozen_string_literal: true

class Counter < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/counters_controller.rb
# frozen_string_literal: true

class CountersController < ApplicationController
  def show
    @str = Counters::CounterStringBuilder.new.call
  end

  def reset
    Counters::CounterResetter.new.call
    redirect_to counter_url
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/counters/show.html.erb
<h3>WebCounter</h3>
<%= button_to 'Reset counter', reset_counter_path, method: :post %>
<p id="strContainer"><%= @str %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webcounter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>